### PR TITLE
fix: reset password

### LINKED ISSUE #227: Bug: Reset Password Functionality Not Working
### Description
The reset password feature does not function as expected and fails to allow password reset.

### Environment

- Operating System: Windows 10

- Browser and version: Google Chrome 127.0

### Expected Behaviour
The system should allow users to reset their password successfully.

### Steps to Reproduce

- Navigate to the "user/profile" page.
- Click the Security setting.
- Add a new password
- Submit the form.

### PR DESCRIPTION
**Pull request by Kingcedru**
### Describe your changes

- The reset password feature does not function as expected and fails to allow password reset.

### Issue ticket number and link

- #227 

### Checklist before requesting a review

- [x] Resetting a password works very well.
- [x] I have performed a self-review of my code
- [x] No existing features have been broken without good reason.

### CODE REVIEW

**Review by divinecharlotte — DISMISSED** [review]

File: apps/drec-api/src/guards/WithoutAuthGuard.ts [hunk 1]
```diff
@@ -31,15 +31,13 @@ export class WithoutAuthGuard implements CanActivate {
     let user: IUser;
 
     if (request.url.split('/')[3] === 'forget-password') {
-      user = await this.userService.findByEmail(request.body.email);
+      user = await this.userService.findByEmail(request.params.email);
```
Comment (musayann) [inline apps/drec-api/src/guards/WithoutAuthGuard.ts]: isn't this post request ?

File: apps/drec-api/src/guards/WithoutAuthGuard.ts [hunk 2]
```diff
@@ -31,15 +31,13 @@ export class WithoutAuthGuard implements CanActivate {
...
     } else if (
       request.url.split('/')[3] === 'confirm-email' ||
       request.url.split('/')[3] === 'reset'
     ) {
       user = (
-        await this.emailConfirmationService.findOne({
-          token: request.params.token,
-        })
+        await this.emailConfirmationService.getByEmail(request.params.token)
```
Comment (musayann) [inline apps/drec-api/src/guards/WithoutAuthGuard.ts]: Please revert to the implementation that was here before

File: apps/drec-api/src/guards/WithoutAuthGuard.ts (hunk 1 above)
Comment (musayann) [reply apps/drec-api/src/guards/WithoutAuthGuard.ts]: this should stay as a post request and the email should come from the `body`

**Review by musayann — CHANGES_REQUESTED** [review]

**Review by divinecharlotte — DISMISSED** [review]

File: apps/drec-api/src/guards/WithoutAuthGuard.ts [hunk 3]
```diff
@@ -25,75 +28,88 @@ export class WithoutAuthGuard implements CanActivate {
...
+
+      case UrlPath.Login:
+        user = await this.userService.findByEmail(request.body.username);
+        break;
+
+      default:
+        break;
     }
 
+    const getAdminApiUserId = (
```
Comment (musayann) [inline apps/drec-api/src/guards/WithoutAuthGuard.ts]: this variable shouldn't be named like a function. it shouldn't include the keyword `get`. It's not getting anything it has already the value by the time it's going to be used

**Review by musayann — CHANGES_REQUESTED** [review]

File: apps/drec-api/src/guards/WithoutAuthGuard.ts [hunk 4]
```diff
@@ -25,75 +28,88 @@ export class WithoutAuthGuard implements CanActivate {
...
+      default:
+        break;
     }
 
+    const adminApiUserId = (
+      (await this.userService.findOne({ role: Role.Admin })) as IUser
+    ).api_user_id;
+
     if (
-      request.body.organizationType === undefined &&
```
Comment (musayann) [inline apps/drec-api/src/guards/WithoutAuthGuard.ts:83]: why did you remove this check ?

**Review by musayann — CHANGES_REQUESTED** [review]

File: apps/drec-api/src/guards/WithoutAuthGuard.ts (hunk 4 above)
Comment (Kingcedru) [reply apps/drec-api/src/guards/WithoutAuthGuard.ts:83]: No reason, I'm going to add it back.

**Review by musayann — APPROVED** [review]
